### PR TITLE
Add tests and fix arg quoting

### PR DESCRIPTION
**Pull request by ViViDboarder**
Added some tests first to make sure this works.

This patch also updates `push.sh` to use a bash array of arguments rather than passing them all as strings.

### CODE REVIEW

**Comment by ViViDboarder** [comment]
@6543 @opyale FYI

**Comment by 6543** [comment]
thanks - I'll test this tomorow

**Comment by ghost** [comment]
@ViViDboarder thank you.

**Comment by 6543** [comment]
works

**Review by 6543 — APPROVED** [review]
and we finaly have tests :)

**Comment by 6543** [comment]
so this close #8 and #9

**Pull request merged**
