### PR TITLE
Update readme & Add docs.md

### PR DESCRIPTION
**Pull request by 6543**
this modernize the readme,  
fix some links and  
make it possible to list at https://woodpecker-ci.org/plugins via docs.md

### CODE REVIEW

**Comment by 6543** [comment]
@ViViDboarder 👋

**Comment by ViViDboarder** [comment]
Thanks!

**Comment by 6543** [comment]
thanks - happy holidays by the way :)

**Comment by 6543** [comment]
@ViViDboarder -> https://woodpecker-ci.org/plugins/WebDAV :)

**Pull request merged**
