### PR TITLE
Fix author key

### PR DESCRIPTION
**Pull request by qwerty287**
The key must be `author` (singular).

### CODE REVIEW

**Comment by qwerty287** [comment]
Hey @vividboarder, did you miss this?

**Comment by ViViDboarder** [comment]
I stated looking into it, but couldn’t find any documentation suggesting what this field should be called. Could you link to that?

**Comment by qwerty287** [comment]
Unfortunately, there's no documentation for this yet.

You can take a look at https://github.com/woodpecker-ci/woodpecker/blob/main/docs/plugins/woodpecker-plugins/src/types.ts#L6 though, that's the type used for parsing the header - it's singular.

**Comment by qwerty287** [comment]
I opened an issue: https://github.com/woodpecker-ci/woodpecker/issues/3230

**Comment by ViViDboarder** [comment]
Thanks!

**Pull request merged**
